# MIT License
# 
# Copyright (c) 2025 Jeroen Ooms, and Eli Lilly and Comany
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

on:
  workflow_dispatch:

name: Create Production Snapshot

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install rversions.
        shell: Rscript {0}
        run: install.packages("rversions")

      - name: Record production snapshot date.
        run: date +%F > date.txt

      - name: Record staging freeze date.
        run: date -d "1 month ago" +"%Y-%m-15" > staging.txt

      - name: Record snapshot R version.
        shell: Rscript {0}
        run: writeLines(rversions::r_release()$version, "r_version.txt")

      - name: Save snapshot URL.
        run: curl "https://raw.githubusercontent.com/r-multiverse/staging/main/snapshot.url" -Lo snapshot.url

      - name: Clean files.
        run: rm -rf .github README.md bin src

      - name: Push to the snapshot branch.
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean: false
          branch: snapshot
          folder: .
